# Generated by Django 3.1.2 on 2020-10-14 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cookieval',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
